### PR TITLE
Rebase

### PR DESCRIPTION
**Pull request by BRONSOLO**
Targetting the updated `main` branch for this work.

### CODE REVIEW

**Comment by BRONSOLO** [comment]
@agateaux I'm reopening this one to address the conflicts. Would you mind taking a look? FYI this was already merged in https://github.com/plotly/paketo-buildpacks_poetry-install/pull/2 before the branch fixes for the release flow.

**Comment by agateaux** [comment]
> @agateaux I'm reopening this one to address the conflicts. Would you mind taking a look? FYI this was already merged in #2 before the branch fixes for the release flow.

Ok, done

**Comment by agateaux** [comment]
Pr for 5.4 created here: https://github.com/plotly/paketo-buildpacks_poetry-install/pull/5

**Review by agateaux — APPROVED** [review]

**Comment by BRONSOLO** [comment]
Thx!

**Pull request merged**
